name: Post to Qiita

on:
  push:
    paths:
      - 'qiita_posts/**'  # qiita_postsディレクトリ内のファイルが変更されたときにトリガーされる
  workflow_dispatch: # 手動も可能

jobs:
  post_to_qiita:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # リポジトリの最新2件の履歴を取得

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Post or Update Qiita Articles
        env:
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_API_TOKEN }}
        run: python .github/scripts/sync_qiita.py

      - name: Check for changes in qiita_article_ids.json
        id: check_changes
        run: |
          changes=$(git status --short | grep "qiita_article_ids.json" || true)
          if [ -z "$changes" ]; then
            echo "No changes detected in qiita_article_ids.json"
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Changes detected in qiita_article_ids.json"
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Commit updated article IDs
        if: env.continue == 'true' # 変更があった場合にのみ実行
        run: |
          echo "Handling changes..."
          # 必要なスクリプトやコマンドをここに追加
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add qiita_article_ids.json
          git commit -m "Update qiita_article_ids.json"
          git push
